export const isValidEmail = (email: string): boolean => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
};

// List of common disposable email domains
const disposableDomains = [
    "temp-mail.org",
    "10minutemail.com",
    "guerrillamail.com",
    "yopmail.com",
    "mailinator.com",
    "getnada.com",
    "tempmail.com",
    "burnermail.io",
    "throwawaymail.com",
    "fakemail.net",
    "sharklasers.com",
    "guerillamail.info",
    "grr.la",
    "guerrillamail.biz",
    "guerrillamail.com",
    "guerrillamail.de",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamailblock.com",
    "pokemail.net",
    "spam4.me",
    "0815.ru",
    "10minutemail.co.uk",
    "10minutemail.net",
    "1secmail.com",
    "1secmail.net",
    "1secmail.org",
    "33mail.com",
    "beefmilk.com",
    "boun.cr",
    "brefmail.com",
    "bsnow.net",
    "bugmenot.com",
    "ce.mintemail.com",
    "classesmail.com",
    "clickemail.com",
    "contact-alias.com",
    "convoy.com",
    "dayrep.com",
    "discard.email",
    "discardmail.com",
    "discardmail.de",
    "disposable.com",
    "dispostable.com",
    "dodgit.com",
    "drdrb.com",
    "eelmail.com",
    "einrot.com",
    "emailondeck.com",
    "etranquil.com",
    "fleckens.hu",
    "gustr.com",
    "harakirimail.com",
    "hushmail.com",
    "imgof.com",
    "incognitomail.org",
    "jourrapide.com",
    "lortap.com",
    "mailcatch.com",
    "mailimate.com",
    "mailnesia.com",
    "mailnull.com",
    "moakt.com",
    "mohmal.com",
    "my10minutemail.com",
    "mytrashmail.com",
    "nomail.xl.cx",
    "nospam.today",
    "owlymail.com",
    "pancakemail.com",
    "rhyta.com",
    "s0ny.net",
    "safetymail.info",
    "shitmail.org",
    "sogetthis.com",
    "spambox.us",
    "spamgourmet.com",
    "spamhole.com",
    "spaml.com",
    "spammotel.com",
    "superrito.com",
    "teleworm.us",
    "temp-mail.ru",
    "tempmail.net",
    "tempmailaddress.com",
    "tempthethrowaway.com",
    "throwawaymail.com",
    "trashmail.com",
    "trashmail.net",
    "trbvm.com",
    "ureg.in",
    "yomail.info",
    "zetmail.com",
];

export const isDisposableEmail = (email: string): boolean => {
    if (!isValidEmail(email)) return false;
    const domain = email.split("@")[1].toLowerCase();
    return disposableDomains.includes(domain);
};
